---
- name: install commandline tools
  apt: name={{ item }}
  sudo: yes
  with_items:
    - bridge-utils
    - curl
    - dstat
    - fabric
    - geary
    - htop
    - mr
    - mu4e
    - nfs-common
    - p7zip-full
    - suckless-tools
    - sysstat
    - tmux
    - uml-utilities
    - vlan
    - vcsh
    - whois
    - vim
    - mpd
  tags: [tools]

- name: sync my tools
  synchronize: src=bin dest=~/local recursive=yes
  tags: [tools]
