- name: apply my basic configuration and tools to all nodes
  hosts: '{{ target }}'

  roles:
    - configuration
    - tool

- name: desktop
  hosts: desktop
  roles:
    - desktop
    - multipkg
    - libvirt
