---

- name: add users
  user: name="{{ item.key }}" shell="{{ item.value.shell | default("/bin/bash") }}" groups="{{ item.value.groups | default([]) | join(",") }}" password="{{ item.value.password }}"
  sudo: yes
  with_dict: users
  tags: [users]

- name: sync users authorized_keys
  authorized_key: user="{{ item.key }}" key="{{ item.value.sshkey }}" manage_dir=yes
  with_dict: users
  tags: [users]

- name: sync users home configurations
  synchronize: src=users/{{ item.key }}/home/ dest=/home/{{ item.key }}/ dirs=yes rsync_opts="--no-perms"
  with_dict: users
  tags: [users]
